inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.1.10

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Max: 27

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# Annotated tokens harm readability in 90% of format strings.
Style/FormatStringToken:
  Enabled: false

# Too subtle to lint. Prefer normal conditionals, except on very simple lines.
Style/IfUnlessModifier:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

